### ISSUE TITLE
Encountering Error When Running choropleth_example.py

### ISSUE THREAD

**Issue by steve98654** [ConnectedSystems/Dash-Choropleth-Example#1]
Hey there,

I am trying to run your choropleth example on Ubuntu 16.04 and built a conda environment that includes all packages in your .yml file with the exception of a few windows specific packages that were not available on linux.  When trying to run, I am encountering the below error.  Any ideas on how to resolve?

steve@Riemann:~/Repos/Dash-Choropleth-Example$ source activate choro-example
(choro-example) steve@Riemann:~/Repos/Dash-Choropleth-Example$ python choropleth_example.py 
Traceback (most recent call last):
  File "choropleth_example.py", line 26, in <module>
    raise RuntimeError("Mapbox key not specified! Edit this file and add it.")
RuntimeError: Mapbox key not specified! Edit this file and add it.
(choro-example) steve@Riemann:~/Repos/Dash-Choropleth-Example$

**Comment by ConnectedSystems** [comment]
Hi @steve98654 

As the error suggests, the example uses the [mapbox platform](https://www.mapbox.com).

You have to create an account and get an API key, then edit the example file (`choropleth_example.py`) and specify your access key.

Otherwise you can rewrite that section to use some other map service. The reason I'm using mapbox is because 1) the example I based this on used it and 2) I wanted to create the example as quickly as possible.

**Comment by steve98654** [comment]
Should have guessed that :)  It is working now; thanks for your help!

**Comment by steve98654** [comment]
FYI, your example works on my ubuntu version with a conda env generated
from the attached .yml.  Here is version info:

Linux version 4.10.0-33-generic (buildd@lgw01-22) (gcc version 5.4.0
20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #37~16.04.1-Ubuntu SMP Fri Aug
11 14:07:24 UTC 2017

Thought it may be helpful since you mentioned you did not test on *nix
systems

**Comment by ConnectedSystems** [comment]
Hi @steve98654 

Thanks - I don't see an attachment but that could be because I'm on my phone. I'll update the repo with your environment file when I can, with you credited of course.

**Comment by ConnectedSystems** [comment]
Hi @steve98654 , finally found the time to have a look at this. I cannot see any yml file attached to your last comment - could you please attach it, or submit a PR please?

Thanks for your help.

**Comment by steve98654** [comment]
Hey Takuya,

I have attached it again to this email in case it is not going though with
github.

Steve

**Comment by ConnectedSystems** [comment]
Hi again @steve98654 

Looks like github strips email attachments - could you submit a PR instead please? 

Thanks again

**Comment by steve98654** [comment]
Just forked and submitted a PR.

**Comment by ConnectedSystems** [comment]
Merged #2 and closing. Thanks again for your contribution.
